### ISSUE TITLE
You stumbled into a problem with Zig SDK that bazel-zig-cc was not able to fix

### ISSUE THREAD

**Issue by farcop** [uber/hermetic_cc_toolchain#105]
MacOS M1

https://github.com/ziglang/zig/issues/14978

That code builds on another PCs well, `bazel clean --expunge` does not help.
Error message contains that "hermetic_cc_toolchain has a workaround" but what is it?

```
% bazel build //...
DEBUG: /private/var/tmp/_bazel_farcop/e66529431dbede3bc951f821053136ab/external/hermetic_cc_toolchain/toolchain/defs.bzl:182:18: Launcher compilation failed. Retrying build
DEBUG: /private/var/tmp/_bazel_farcop/e66529431dbede3bc951f821053136ab/external/hermetic_cc_toolchain/toolchain/defs.bzl:182:18: Launcher compilation failed. Retrying build
INFO: Repository zig_sdk instantiated at:
  /Users/farcop/Sources/kublr/WORKSPACE:326:15: in <toplevel>
  /private/var/tmp/_bazel_farcop/e66529431dbede3bc951f821053136ab/external/hermetic_cc_toolchain/toolchain/defs.bzl:80:19: in toolchains
Repository rule zig_repository defined at:
  /private/var/tmp/_bazel_farcop/e66529431dbede3bc951f821053136ab/external/hermetic_cc_toolchain/toolchain/defs.bzl:218:33: in <toplevel>
INFO: repository @zig_sdk' used the following cache hits instead of downloading the corresponding file.
 * Hash '19f9115410a6dfb004c65d63ffecf947efc595d08977906f73a90d7b2de0b3dc' for https://mirror.bazel.build/ziglang.org/builds/zig-macos-aarch64-0.11.0-dev.3312+ab37ab33c.tar.xz
If the definition of 'repository @zig_sdk' was updated, verify that the hashes were also updated.
ERROR: An error occurred during the fetch of repository 'zig_sdk':
   Traceback (most recent call last):
	File "/private/var/tmp/_bazel_farcop/e66529431dbede3bc951f821053136ab/external/hermetic_cc_toolchain/toolchain/defs.bzl", line 205, column 13, in _zig_repository_impl
		fail(zig_wrapper_err_msg)
Error in fail: 
Compilation of zig-wrapper.zig failed:
command=ZIG_LOCAL_CACHE_DIR=/tmp/zig-cache ZIG_GLOBAL_CACHE_DIR=/tmp/zig-cache ../zig build-exe -mcpu=apple_a14 -OReleaseSafe zig-wrapper.zig
return_code=1
stderr=error: FileNotFound

stdout=

You stumbled into a problem with Zig SDK that bazel-zig-cc was not able to fix.
Please file a new issue to github.com/uber/hermetic_cc_toolchain with:
- Full output of this Bazel run, including the Bazel command.
- Version of the Zig SDK if you have a non-default.
- Version of hermetic_cc_toolchain

Note: this *may* have been https://github.com/ziglang/zig/issues/14978, for
which hermetic_cc_toolchain has a workaround and you may have been "struck by
lightning" three times in a row.
ERROR: /Users/farcop/Sources/kublr/WORKSPACE:326:15: fetching zig_repository rule //external:zig_sdk: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_farcop/e66529431dbede3bc951f821053136ab/external/hermetic_cc_toolchain/toolchain/defs.bzl", line 205, column 13, in _zig_repository_impl
		fail(zig_wrapper_err_msg)
Error in fail: 
Compilation of zig-wrapper.zig failed:
command=ZIG_LOCAL_CACHE_DIR=/tmp/zig-cache ZIG_GLOBAL_CACHE_DIR=/tmp/zig-cache ../zig build-exe -mcpu=apple_a14 -OReleaseSafe zig-wrapper.zig
return_code=1
stderr=error: FileNotFound

stdout=

You stumbled into a problem with Zig SDK that bazel-zig-cc was not able to fix.
Please file a new issue to github.com/uber/hermetic_cc_toolchain with:
- Full output of this Bazel run, including the Bazel command.
- Version of the Zig SDK if you have a non-default.
- Version of hermetic_cc_toolchain

Note: this *may* have been https://github.com/ziglang/zig/issues/14978, for
which hermetic_cc_toolchain has a workaround and you may have been "struck by
lightning" three times in a row.
INFO: Repository search-guard-suite-plugin-sgadmin-standalone-multiarch instantiated at:
  /Users/farcop/Sources/kublr/WORKSPACE:390:25: in <toplevel>
  /Users/farcop/Sources/kublr/nonhermetic/defs.bzl:36:17: in nonhermetic_dependencies
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_farcop/e66529431dbede3bc951f821053136ab/external/bazel_tools/tools/build_defs/repo/http.bzl:372:31: in <toplevel>
ERROR: Analysis of target '//cluster-management-frontend/app/kublr-common:test' failed; build aborted: 
Compilation of zig-wrapper.zig failed:
command=ZIG_LOCAL_CACHE_DIR=/tmp/zig-cache ZIG_GLOBAL_CACHE_DIR=/tmp/zig-cache ../zig build-exe -mcpu=apple_a14 -OReleaseSafe zig-wrapper.zig
return_code=1
stderr=error: FileNotFound

stdout=

You stumbled into a problem with Zig SDK that bazel-zig-cc was not able to fix.
Please file a new issue to github.com/uber/hermetic_cc_toolchain with:
- Full output of this Bazel run, including the Bazel command.
- Version of the Zig SDK if you have a non-default.
- Version of hermetic_cc_toolchain

Note: this *may* have been https://github.com/ziglang/zig/issues/14978, for
which hermetic_cc_toolchain has a workaround and you may have been "struck by
lightning" three times in a row.
INFO: Elapsed time: 25.519s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1055 packages loaded, 63374 targets configured)
```

**Comment by elchead** [comment]
Had the same issue on M2 with 13.5. I did an upgrade to 13.5.1 and it's working again. Might have been that a reboot was enough.

**Comment by sasha-wing** [comment]
Had the same issue on my linux CI worker and a reboot solved it.

Thank you @elchead !

```
 Operating System: Debian GNU/Linux 11 (bullseye)
            Kernel: Linux 5.10.0-25-cloud-amd64
      Architecture: x86-64
```

**Comment by farcop** [comment]
After upgrade Macos on Sonoma 14.0 reboot does not helps...

**Comment by motiejus** [comment]
Which version of hermetic_cc_toolchain are you using?

**Comment by farcop** [comment]
@motiejus v2.0.0
I cant use v2.1.2  because of https://github.com/uber/hermetic_cc_toolchain/issues/122

**Comment by motiejus-wix** [comment]
Please only report only issues with either the released version or the current master.

**Comment by farcop** [comment]
@motiejus-wix A strange remark, considering the fact that this issue was created for the latest release at that time of creation.

**Comment by motiejus** [comment]
> @motiejus-wix A strange remark, considering the fact that this issue was created for the latest release at that time of creation.

I see.

If this happens again with a toolchain beyond  3a0b2fe448d23195abeccae533eac798dc333b09 (up for the next relase), please create a new issue with more details:
- toolchain version
- if Zig was overwritten, which zig version.
- archive `/tmp/zig-cache` and attach to the issue.
